#!/bin/bash
BOOTKEY="/var/run/boot.key"
if [ -f "$BOOTKEY" ]
then
    echo "already boot!"
else
    echo "set Timezone"
    cp -f /usr/share/zoneinfo/Asia/Seoul /etc/localtime
    service ntpd start

    echo "Nginx Start.."
    service nginx start

    echo "php-fpm start.."
    php-fpm

    #echo OK > $BOOTKEY

    ps aux

fi
